server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-cttu1i3qf0us73ev0ej0-a.singapore-postgres.render.com:5432/database_fullstackapp
    username: fullstackapp_user
    password: m1B0GIMmVWaHVbl0Ckgwlzy8hAneHaQ2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: xiaoming00009@gmail.com
    password: xmhrunotdhgbfjbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  upload: upload/
base:
  url: http://localhost:8080



#    url: jdbc:postgresql://localhost:5432/backend_spring
#    username: postgres
#    password: root